version: '3'
services:
  server:
    build: ./server
    depends_on:
      - db
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules/
  front:
    build: ./front
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
      - /app/node_modules/
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./docker/postgres:/var/lib/postgresql/data

volumes:
  data: